package panificadora.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import panificadora.model.salvarDadosF;

public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro2
     */
    public TelaFuncionario() {
        initComponents();
                        Date da = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd / MM / YYYY"); 
        Data.setText(formato.format(da));
        
        Timer t = new Timer(1000,new TelaFuncionario.horas());
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodigoF = new javax.swing.JTextField();
        NomeF = new javax.swing.JTextField();
        SobreF = new javax.swing.JTextField();
        UserF = new javax.swing.JTextField();
        CpfF = new javax.swing.JFormattedTextField();
        SenhaF = new javax.swing.JPasswordField();
        Cadastrar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        a = new javax.swing.JPanel();
        Hora = new javax.swing.JLabel();
        a1 = new javax.swing.JPanel();
        Data = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LC = new javax.swing.JLabel();
        LN = new javax.swing.JLabel();
        LU = new javax.swing.JLabel();
        Lc1 = new javax.swing.JLabel();
        LS = new javax.swing.JLabel();
        Ls = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionáro");
        setResizable(false);
        getContentPane().setLayout(null);

        CodigoF.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        getContentPane().add(CodigoF);
        CodigoF.setBounds(340, 120, 90, 40);

        NomeF.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        getContentPane().add(NomeF);
        NomeF.setBounds(330, 170, 270, 40);

        SobreF.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        getContentPane().add(SobreF);
        SobreF.setBounds(660, 220, 190, 40);

        UserF.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        getContentPane().add(UserF);
        UserF.setBounds(280, 220, 150, 40);

        try {
            CpfF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CpfF);
        CpfF.setBounds(280, 270, 150, 40);

        SenhaF.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        SenhaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaFActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaF);
        SenhaF.setBounds(660, 270, 170, 40);

        Cadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar);
        Cadastrar.setBounds(370, 500, 130, 50);

        limpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        getContentPane().add(limpar);
        limpar.setBounds(100, 420, 130, 50);

        pesquisar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(630, 430, 160, 50);

        alterar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(370, 430, 130, 50);

        excluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(100, 490, 130, 50);

        Atualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar);
        Atualizar.setBounds(630, 500, 160, 50);

        a.setBackground(new java.awt.Color(0, 0, 0));
        a.setForeground(new java.awt.Color(204, 0, 0));

        Hora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 0, 0));
        a.add(Hora);

        getContentPane().add(a);
        a.setBounds(730, 30, 120, 40);

        a1.setBackground(new java.awt.Color(0, 0, 0));

        Data.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 0, 0));
        a1.add(Data);

        getContentPane().add(a1);
        a1.setBounds(560, 30, 150, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/arrow_undo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 90, 40);

        L1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        L1.setText("Cadastro de Funcionários");
        getContentPane().add(L1);
        L1.setBounds(100, 30, 450, 42);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/fundoAmarelo.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(-30, 0, 920, 80);

        LC.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LC.setForeground(new java.awt.Color(255, 255, 153));
        LC.setText("Código do funcionário:");
        getContentPane().add(LC);
        LC.setBounds(50, 120, 290, 30);

        LN.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LN.setForeground(new java.awt.Color(255, 255, 153));
        LN.setText("Nome do Funcionário:");
        getContentPane().add(LN);
        LN.setBounds(50, 170, 270, 40);

        LU.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LU.setForeground(new java.awt.Color(255, 255, 153));
        LU.setText(" Usuário:");
        getContentPane().add(LU);
        LU.setBounds(120, 220, 120, 40);

        Lc1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Lc1.setForeground(new java.awt.Color(255, 255, 153));
        Lc1.setText("Cpf:");
        getContentPane().add(Lc1);
        Lc1.setBounds(160, 270, 70, 30);

        LS.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LS.setForeground(new java.awt.Color(255, 255, 153));
        LS.setText("Sobrenome:");
        getContentPane().add(LS);
        LS.setBounds(490, 220, 160, 40);

        Ls.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Ls.setForeground(new java.awt.Color(255, 255, 153));
        Ls.setText("Senha:");
        getContentPane().add(Ls);
        Ls.setBounds(520, 270, 100, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 120, 320, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 170, 300, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 220, 260, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(40, 270, 270, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(480, 220, 190, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(460, 270, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/fundoLogin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 400, 880, 170);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/fundoCadastroFornecedor.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-50, -30, 940, 630);

        setSize(new java.awt.Dimension(904, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        salvarDadosF sd = new salvarDadosF();

        sd.setCodigo(CodigoF.getText());
        sd.setNome(NomeF.getText());
        sd.setCpf(CpfF.getText());
        sd.setUsuario(UserF.getText());
        sd.setSenha(String.valueOf(SenhaF.getPassword()));
        sd.setSobrenome(SobreF.getText());
        
        if(CodigoF.getText().equals("") || NomeF.getText().equals("") || CpfF.getText().equals("") || UserF.getText().equals("") || SenhaF.getPassword().equals("") ||  SobreF.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Alguns campos não foram preenchidos","Aviso",JOptionPane.ERROR_MESSAGE);
        
        }else{
            JOptionPane.showMessageDialog(null, sd.SalvaDados());
        }

        CodigoF.setEnabled(true);
        CodigoF.setText("");
        NomeF.setText("");
        UserF.setText("");
        CpfF.setText("");
        SobreF.setText("");
        SenhaF.setText("");
    }//GEN-LAST:event_CadastrarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        CodigoF.setText("");
        NomeF.setText("");
        UserF.setText("");
        CpfF.setText("");
        SobreF.setText("");
        SenhaF.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        if(evt.getSource() == pesquisar){
            try{
                String codigo = JOptionPane.showInputDialog("Digite o Código:");

                BufferedReader ler = new BufferedReader(new FileReader("../Panificadora/Funcionarios/Funcionario"+codigo+".txt"));

                SenhaF.setText(ler.readLine());
                UserF.setText(ler.readLine());
                CodigoF.setText(ler.readLine());
                NomeF.setText(ler.readLine());
                CpfF.setText(ler.readLine());
                SobreF.setText(ler.readLine());
                ler.close();

            }catch(Exception erro){
                JOptionPane.showMessageDialog(null, "Erro: "+erro.getMessage());
            }
            NomeF.setEnabled(false);
            SobreF.setEnabled(false);
            CpfF.setEnabled(false);
            UserF.setEnabled(false);
            SenhaF.setEnabled(false);
            CodigoF.setEnabled(false);
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        NomeF.setEnabled(true);
        SobreF.setEnabled(true);
        CpfF.setEnabled(true);
        UserF.setEnabled(true);
        SenhaF.setEnabled(true);
        CodigoF.setEnabled(false);
    }//GEN-LAST:event_alterarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        salvarDadosF ne = new salvarDadosF();
        String codigos = JOptionPane.showInputDialog("Digite o Código: ");
       
            JOptionPane.showMessageDialog(null, ne.Excluir(codigos));
        
        

    }//GEN-LAST:event_excluirActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        salvarDadosF sd = new salvarDadosF();

        sd.setCodigo(CodigoF.getText());
        sd.setNome(NomeF.getText());
        sd.setCpf(CpfF.getText());
        sd.setUsuario(UserF.getText());
        sd.setSenha(String.valueOf(SenhaF.getPassword()));
        sd.setSobrenome(SobreF.getText());
        
        if(CodigoF.getText().equals("") || NomeF.getText().equals("") || CpfF.getText().equals("") || UserF.getText().equals("") || SenhaF.getPassword().equals("") ||  SobreF.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Alguns campos não foram preenchidos","Aviso",JOptionPane.ERROR_MESSAGE);
        
        }else{
             JOptionPane.showMessageDialog(null, sd.Atualizar());
        }

       

        CodigoF.setEnabled(true);
        CodigoF.setText("");
        NomeF.setText("");
        UserF.setText("");
        CpfF.setText("");
        SobreF.setText("");
        SenhaF.setText("");

    }//GEN-LAST:event_AtualizarActionPerformed

    private void SenhaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Home a = new Home();
    a.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField CodigoF;
    private javax.swing.JFormattedTextField CpfF;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel LC;
    private javax.swing.JLabel LN;
    private javax.swing.JLabel LS;
    private javax.swing.JLabel LU;
    private javax.swing.JLabel Lc1;
    private javax.swing.JLabel Ls;
    private javax.swing.JTextField NomeF;
    private javax.swing.JPasswordField SenhaF;
    private javax.swing.JTextField SobreF;
    private javax.swing.JTextField UserF;
    private javax.swing.JPanel a;
    private javax.swing.JPanel a1;
    private javax.swing.JButton alterar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limpar;
    private javax.swing.JButton pesquisar;
    // End of variables declaration//GEN-END:variables
    public class horas implements ActionListener{
    @Override
    public void actionPerformed (ActionEvent e){
        Calendar c = Calendar.getInstance();
        Hora.setText(String.format("%1$tH:%1$tM:%1$tS", c));
    }
    }
}
